name: Release Swiftcomplete

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  set-version:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"
